name: md2_tab_indicator
description: MD2TabIndicator is a tab indicator influenced by Google's Material
  Design 2 tab indicator design and developed by
version: 2.0.0-nullsafety
author: westdabestdb <westdabestdb@gmail.com>
homepage: https://github.com/westdabestdb/md2-tab-indicator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.2

flutter: null
